### ISSUE TITLE
the package doesn't support esm

### ISSUE THREAD

**Issue by xiefucai** [aeyoll/imagemin-avif-webpack-plugin#1]
Error [ERR_REQUIRE_ESM]: require() of ES Module E:\razer\janethyperspeed\node_modules\imagemin\index.js from E:\razer\janethyperspeed\node_modules\imagemin-avif-webpack-plugin\plugin.js not supported.
Instead change the require of index.js in E:\razer\janethyperspeed\node_modules\imagemin-avif-webpack-plugin\plugin.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (E:\razer\janethyperspeed\node_modules\imagemin-avif-webpack-plugin\plugin.js:1:18)
    at Object.<anonymous> (E:\razer\janethyperspeed\config-overrides.js:8:34)
    at Object.<anonymous> (E:\razer\janethyperspeed\node_modules\react-app-rewired\config-overrides.js:5:18)
    at Object.<anonymous> (E:\razer\janethyperspeed\node_modules\react-app-rewired\overrides\paths.js:2:19)
    at Object.<anonymous> (E:\razer\janethyperspeed\node_modules\react-app-rewired\scripts\build.js:6:1) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.12.1

**Comment by aeyoll** [comment]
Hello @xiefucai,
It should be fixed in the 0.0.4 version.
